
version: '3.2'

services:
  mongo:
    image: mongo

    logging:
      driver: none

    ports:
      - "27017:27017"

  redis:
    image: redis

    logging:
      driver: none

    ports:
      - "6379:6379"

  game:
    command: bash -c "apt-get update && apt-get install -y build-essential && npm install && npm run setup && npm run start"
    working_dir: /usr/src/app

    image: "node:12"

    ports:
      - "6975:6975"
      - "4567:4567"

    environment:
      TS_NODE_TRANSPILE_ONLY: 1
      DATABASE_URI: mongodb://mongo:27017

    depends_on:
      - mongo
      - redis

    volumes:
      - type: bind
        source: .
        target: /usr/src/app